//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Erp.BusinessManager
{
    using System;
    using System.ServiceModel;
    using System.ServiceModel.Channels;
    using System.Runtime.Serialization;
    using System.ServiceModel.Web;
    using System.Data;
    
    
    // 테이블('Customers')에 관한 Entity 클래스
    // 여기 코드는 용도에 맞게 변경하여 사용하시오
    // 
    [DataContract()]
    [KnownType(typeof(System.DBNull))]
    public class Customer : CustomerBase
    {
        
        public Customer()
        {
        }
        
        public static void Empty()
        {
            Service.Empty();
        }

        public static DataSet GetAllData(string customerShortName)
        {
            return Service.GetAllData(customerShortName);

        }

        public static DataSet GetCustomerCodeNameInfo(string text)
        {
            throw new NotImplementedException();
        }

        public static DataSet Get원재료재고공급업체()
        {
            return Service.Get원재료재고공급업체();
        }
        public static DataSet GetAllData율촌구매(string customerShortName)
        {
            return Service.GetAllData율촌구매(customerShortName);

        }
        public static DataSet GetCodeName()
        {
            return Service.GetCodeName();

        }

        public static DataSet GetCustomerData(string CustomerCode)
        {
            return Service.GetCustomerData(CustomerCode);

        }
        public static DataSet GetFindByCustomerCode(string CustomerCode)
        {
            return Service.GetFindByCustomerCode(CustomerCode);

        }
    }
}
