//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Erp.BusinessManager
{
    using System;
    using System.ServiceModel;
    using System.ServiceModel.Channels;
    using System.Runtime.Serialization;
    using System.ServiceModel.Web;
    using System.Data;
    
    
    // 테이블('Customers')에 관한 Proxy 클래스
    // 여기 코드는 용도에 맞게 변경하여 사용하시오
    // 
    public class CustomerProxy : ClientBase<CustomerInterface>, CustomerInterface
    {
        
        public CustomerProxy(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress address) : 
                base(binding, address)
        {
        }
        
        public void Empty()
        {
            base.Channel.Empty();
        }

        public DataSet GetAllData(string customerShortName)
        {
            return base.Channel.GetAllData(customerShortName);
        }

        public DataSet Get원재료재고공급업체()
        {
            return base.Channel.Get원재료재고공급업체();
        }
        public DataSet GetAllData율촌구매(string customerShortName)
        {
            return base.Channel.GetAllData율촌구매(customerShortName);

        }
        public DataSet GetCodeName()
        {
            return base.Channel.GetCodeName();

        }

        public DataSet GetCustomerData(string CustomerCode)
        {
            return base.Channel.GetCustomerData(CustomerCode);

        }
        public DataSet GetFindByCustomerCode(string CustomerCode)
        {
            return base.Channel.GetFindByCustomerCode(CustomerCode);

        }

    }
}
