//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Erp.BusinessManager
{
    using System;
    using System.ServiceModel;
    using System.ServiceModel.Channels;
    using System.Runtime.Serialization;
    using System.ServiceModel.Web;
    using System.Data;
    
    
    // 테이블('Location')에 관한 Entity 클래스
    // 여기 코드는 용도에 맞게 변경하여 사용하시오
    // 
    [DataContract()]
    [KnownType(typeof(System.DBNull))]
    public class Location : LocationBase
    {
        
        public Location()
        {
        }
        
        public static void Empty()
        {
            Service.Empty();
        }

        public static DataSet GetLocationFromNo(int locationNo)
        {
            return Service.GetLocationFromNo(locationNo);
        }

        public override string ToString()
        {
            return this.LocationNo + ": " + this.LocationName;
        }

        public static LocationSet GetForLocationType(int locationType)
        {
            return Service.GetForLocationType(locationType);
        }

        public static LocationSet Get구매창고()
        {
            return Service.Get구매창고();
        }

        public static DataSet GetLocationData(int locationNo)
        {
            return Service.GetLocationData(locationNo);
        }

        public static DataSet GetLocationName()
        {
            return Service.GetLocationName();
        }
    }
}
